### ISSUE TITLE
chat model change

### ISSUE THREAD

**Issue by mpdev0** [jackmcguire1/alexa-chatgpt#17]
what is the intent configuration to enable the ability to select the chat model with "use gemini" or "use gpt"?

**Comment by jackmcguire1** [comment]
hi @mpdev0, repeat steps 4,5 of the setup, i will document this soon!

```
1. Create a new Intent named 'Model'
2. Add a new Alexa slot to this Intent and name it 'chatModel' with type AMAZON.SearchQuery'
3. Create a sample utterance with 'model {chatModel}'
4.  save and rebuild Alexa skill model

```

![image](https://github.com/jackmcguire1/alexa-chatgpt/assets/9089342/2250d674-58ba-46de-a488-81432e2aaca2)

**Comment by jackmcguire1** [comment]
The same also for the ```LastResponse```, which is critical for getting a delayed model responses!

![image](https://github.com/jackmcguire1/alexa-chatgpt/assets/9089342/5b6a55f4-e1fa-4fab-af3b-a2f5b4696e1d)
